### PR TITLE
Bug fixes to manual schedules

### PR DESCRIPTION
**Pull request by Allybe**
Hi!
The admin page wasn't getting the manual schedule games so I fixed it.

### CODE REVIEW

**Comment by Allybe** [comment]
please disregard the changes I made to analysis-modules.json

**Comment by gcschmit** [comment]
Will do. Sorry for the delay in accepting the PR. We were out of town at the Heartland Regional.

**Comment by Allybe** [comment]
No problem! Hope the regional went well

**Review by M4RZTI4N — APPROVED** [review]
looks good to me

**Review by maaz-zubair-99 — APPROVED** [review]
was signed in to the wrong account

**Pull request merged**
